name: Example
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/example.yml'
      - 'pyproject.toml'
      - 'PySide6_DAW/**'
      - 'example/**'
jobs:
  example:
    name: Install PySide6-DAW on Python ${{ matrix.python-version }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} and PDM 2.4.9
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: 2.4.9
      - name: Install dependencies
        run: pdm install
      - name: Run example
        run: python -m example
