name: Formatting
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/formatting.yml'
      - 'pyproject.toml'
      - 'PySide6_DAW/**'
jobs:
  isort:
    name: Isort
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10 and PDM 2.4.9
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.10'
          architecture: x64
          version: 2.4.9
      - name: Install dependencies
        run: pdm install --dev
      - name: Run isort
        run: pdm run isort --check PySide6_DAW
  black:
    name: Black
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10 and PDM 2.4.9
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.10'
          architecture: x64
          version: 2.4.9
      - name: Install dependencies
        run: pdm install --dev
      - name: Run black
        run: pdm run black --check PySide6_DAW
