name: Linting
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/linting.yml'
      - 'pyproject.toml'
      - 'PySide6_DAW/**'
jobs:
  pylint:
    name: Pylint on Python ${{ matrix.python-version }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} and PDM 2.4.9
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: 2.4.9
      - name: Install dependencies
        run: pdm install --dev
      - name: Run pylint
        run: pdm run pylint PySide6_DAW
  mypy:
    name: Mypy on Python ${{ matrix.python-version }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} and PDM 2.4.9
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: 2.4.9
      - name: Install dependencies
        run: pdm install --dev
      - name: Run mypy
        run: pdm run mypy PySide6_DAW
